# Generated by Django 5.2.3 on 2026-02-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ValentineVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My Valentine Gift', max_length=100)),
                ('video_file', models.FileField(upload_to='videos/')),
                ('is_active', models.BooleanField(default=True, help_text='Only one video should be active at a time.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
